SET SERVEROUTPUT ON 

DROP TABLE TIENDAS;
CREATE TABLE TIENDAS 
(
    NOMBRE VARCHAR2 (20) UNIQUE,
    POBLACION VARCHAR2 (20),
    CATEGORIAS VARCHAR2 (20),
    CODPOSTAL NUMBER (5),
    CONSTRAINT PK_TIENDAS PRIMARY KEY (NOMBRE),
    CONSTRAINT CH_TIENDANOMBRE CHECK (REGEXP_LIKE(NOMBRE,'^([[:alpha:]])+$'))
);

DROP TABLE VENDEDORES;
CREATE TABLE VENDEDORES
(
    CODIGO VARCHAR2 (3),
    NOMBRE VARCHAR2 (15) NOT NULL,
    PAIS VARCHAR2 (20),
    CONSTRAINT PK_VENDEDORES PRIMARY KEY (CODIGO),
    CONSTRAINT CH_VENDEDORPAIS CHECK (PAIS LIKE UPPER(PAIS))
);

DROP TABLE ARTICULOS;
CREATE TABLE ARTICULOS
(
    CODIGO VARCHAR2 (10),
    NOMBRE VARCHAR2 (15),
    COD_VENDEDOR VARCHAR2 (3),
    PESO NUMBER (3,2),
    ESTADO VARCHAR2 (10),
    PRECIO_VENTA NUMBER (6,2),
    CONSTRAINT PK_ARTICULOS PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CODV_ARTICULOS FOREIGN KEY (COD_VENDEDOR) REFERENCES VENDEDORES (CODIGO),
    CONSTRAINT CH_ARTICULOSESTADO CHECK (ESTADO IN ('Nuevo', 'Reacondicionado', 'Usado')),
    CONSTRAINT CH_ARTICULOSPRECIOV CHECK (PRECIO_VENTA>0)
);