-- ALTERACIÓN DE TABLAS
--1

ALTER TABLE VENDEDORES ADD COLUMN TIPO VARCHAR2(30);

--2

ALTER TABLE VENDEDORES ADD CONSTRAINT CH_VENDEDORTIPO CHECK (TIPO IN ('Franquicia','Autonomo'));

--3 

ALTER TABLE VENDEDORES DROP COLUMN PAIS;

--4 

ALTER TABLE ARTICULOS ADD CONSTRAINT CH_ARTICULOCODIGO CHECK (REGEXP_LIKE(CODIGO,'^([0-9])+$'));

--5 

ALTER TABLE VENDEDORES DROP CONSTRAINT CH_VENDEDORPAIS;

--6 

ALTER TABLE TIENDAS DROP CONSTRAINT CH_TIENDANOMBRE;

INSERT INTO TIENDAS VALUES ('Tienda1', 'Madrid', 'Productos variados', 28000);

ALTER TABLE TIENDAS ADD CONSTRAINT CH_TIENDANOMBRE CHECK (REGEXP_LIKE(NOMBRE,'^([[:alpha:]])+$'));

-- CONSULTAS
--1

SELECT NOMBRE,ESTADO FROM ARTICULOS;

--2

CREATE OR REPLACE VIEW VISTAPEDIDOS AS SELECT SELECT CODIGO,FECHA_PEDIDO FROM PEDIDOS;

--3 

SELECT V.NOMBRE, A.NOMBRE FROM VENDEDORES V, ARTICULOS A WHERE V.CODIGO=A.COD_VENDEDOR;  

--4 Mostrar toda la información de las tiendas y los pedidos.

SELECT T.*, P. LDKGLÑD
